mysql_root_password: 12345
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: 12345
    priv: "notes.*:ALL"